app1/1 lessons/90 login_required, send value of url parametr using post method/code/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/'   ,   admin.site.urls),
    path(''         ,   include('main.urls'   ,   namespace='main')),
    path('catalog/' ,   include('goods.urls'  ,   namespace='catalog')),
    path('user/'    ,   include('users.urls'  ,   namespace='user'))
]

if settings.DEBUG:
    urlpatterns += [  
            path("__debug__/", include("debug_toolbar.urls")),  
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/1 lessons/90 login_required, send value of url parametr using post method/code/users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/',          views.login,            name='login'),
    path('registration/',   views.registration,     name='registration'),
    path('profile/',        views.profile,          name='profile'),
    path('logout/',         views.logout,           name='logout'),
]

app1/1 lessons/90 login_required, send value of url parametr using post method/code/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, You are now logged in")
                # 1) Deməli sayta giriş etmədən URL yerində   'user/profile'   yazdıqda LOGİN.HTML şablonuna yönlənirik və url yerində belə bir link görürük: http://127.0.0.1:8000/user/login/?next=/user/profile/
                # 2) Sonra saytda giriş etmək üçün NAME və PAROL-u daxil edərək ENTER düyməsini basırıq. Bu vaxt ŞABLON-dan, POST metodu vasitəsi ilə URL yerindəki linkin   NEXT    parametrinin   '/user/profile/'   dəyərini 
                #    digər dəyərlər ilə birlikdə ötürmüş oluruq hal-hazırda içində olduğumuz    USERS/VIEWS.PY    controller-inin LOGIN() metoduna. 
                # 
                # 3) Sonra şərt qoşuruq ki, əgər şablondan POST metodu ilə GET() edilən 'NEXT' parametri varsa, RETURN olsun HttpResponseRedirect() metodu.   HttpResponseRedirect() metoduda bizi yönləndirir  'user/profile'  linkinə.
                #   
                #   GET() metodunun 1ci parametri NEXT parametridir. 2ci parametri isə əgər belə bir parametr yoxdursa default olaraq NONE olsun yəni heçnə baş verməsin.
                # 
                #   request.POST.get('next') kodunun bizə verdiyi nəticə 'user/profile' - dir.
                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))
                # 4) Sayta normal LOGİN olaraq daxil olmaq istədikdə onda aşağıdakı   HttpResponseRedirect()  metodu işləyir. LOGİN olmadan URL yerində    'user/profile'    etmək istədikdən  sonra daxil ola bilməyərək LOGİN.HTML 
                #    səhifəsinə yönlənib sonra sayta daxil olmaq istədikdə onda yuxarıdakı  HttpResponseRedirect() metodu işləyir.
                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()
    context = {
        'title' : ' Home - Authorization ',
        'form' : form
    }
    return render( request, 'users/login.html', context )








def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(request, f"{user.username}, You are now registered and logged in")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()
    context = {
        'title' : ' Home - Authentication ',
        'form' : form,
    }
    return render( request, 'users/registration.html', context )


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            messages.success(request, "Profile successfully updated")
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)
    context = {
        'title' : ' Home - Profile ',
        'form' : form,
    }
    return render( request, 'users/profile.html', context )
@login_required


def logout(request):
    messages.success(request, f"{request.user.username}, You are now logged out")
    auth.logout(request)
    return redirect(reverse('main:index'))

app1/1 lessons/90 login_required, send value of url parametr using post method/code/templates/base.html
{% load static %}
{% load goods_tags %} 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"                          href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet"                          href="{% static "deps/css/my_css.css" %}">
    <!-- Footer-a style for the main page -->

    {% block css %}{% endblock  %}

    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180"    href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest"                            href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Information
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Delivery and payment</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Contact Information</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">About us</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Cart</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url "user:login" %}">Log in</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    My profile
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="carts/cart.html">Cart</a></li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Personal account</a></li>
                                    {% if user.is_admin or user.is_staff  %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Admin panel</a></li>
                                    {% endif %}
                                    <li> <hr class="dropdown-divider"> </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Log out</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <section>
        <div class="container">
            <!-- Catalog and cart with a fixed location on the page -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Catalog -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Catalog
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>

                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}      
                    </ul>

                </div>
                <!-- Cart icon, opens a modal window -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Cart Modal Window Layout -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Cart</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Cart layout -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Product</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Total <strong>1</strong> item(s) worth </p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- The cart has finished marking -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Checkout
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Modal window layout finished -->
            </div>
        </div>
        <!-- Content -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Empty block at your discretion -->
                </div>
                <div class="col-lg-10">
                    {% include "includes/notifications.html" %}
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </section>

    {% block footer %}{% endblock footer %}

    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>
</html>